# The Perceptron

What are our learning objectives for this lesson?

* Learn about the Perceptron achitecture
* Learn how to train a Perceptron model 

Content used in this lesson is based upon information in the following sources:
* Marsland, Stephen. Machine Learning: An Algorithmic Perspective 2nd ed. (2015).

## Lab Tasks

1. Initialize weight vector $\vec{w}$ with random values
2. Implement an activation function
3. Implement an update function
4. Train the Perceptron model on the OR operation

### Initialize a weight vector

#### What is the dimensionality of this vector?

Let's first think through the dimensionality of our weight vector. How many entries should it have? Recall that the sum $h$ is given by

$$h = \sum_{i=1}^{m}w_i x_i $$

where $w_i$ is the $i^{th}$ entry of the weight vector $\vec{w}$ and $x_i$ is the $i^{th}$ entry of the input vector $\vec{x}$. This means that for every input value we will need a weight value that goes with it. In another word, if there are $n$ entries in our input vector $\vec{x}$, we will need a weight vector $\vec{w}$ of length $n$. 

Recall that we want to include an additional bias node in our model where the input is always a non-zero value. Since we will be alterning the weight $w_b$ associated with the bias node at the same time as all other nodes in our network, it might be convinient to dedicate a spot in our weight vector $\vec{w}$ that represents the weight $w_0$. Thus, for a problem with $n$ inputs, $\vec{w}$ might look something like this:

$$\vec{w}^T = [w_0, w_1, w_2, ..., w_n]$$

Notice that $\vec{w}$ has a length of $n+1$. 


#### What initial value do we assign the vector?

The initial value we assign the entries in our weight vector $\vec{w}$ matters. If we assign very large values, then $h$ will also be a very large value regardless of our input values (given that input values are not all zeros). If we assign extremely small values, we run into the opposite problem, where $h$ will also be a extremely small value regardless of the input values. We also want to avoid initializing it with all zeros. If you're interested in understanding why, please take a look at this [stackexcahnge response](https://datascience.stackexchange.com/questions/26134/initialize-perceptron-weights-with-zero) that gives a concise explanation. 

In conclusion, it is ideal to have weights that are neither too big or too small. For neural networks (which we will get to soon), The last desired quaility in our initialization values would be non-uniformity. We don't want to assign a single value across the board, and the way to achieve this is by using pseudorandom generators. 

In [2]:
import numpy as np
import math

# define inputs
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
targets = np.array([[0],[1],[1],[1]])

# capture how many nodes are needed by examining
# how many entries is in a set of input
n_in = np.shape(inputs)[1]
        
# how many values are we expecting as output?
# in this case, we want a single value as our output
n_out = 1
        
# η is the rate of which we learn from our data
# typically, 0.1 < η < 0.4
eta = 0.2
        
# TODO: initialize a weight vector
# how long does it have to be?
# what initial values would you assign it?
# self.weights = ???
        
weights = np.random.rand(n_in+1, n_out) * (1 / math.sqrt(n_in+1))
        
print(f'weight vector:\n{weights}')

weight vector:
[[0.46386536]
 [0.2929082 ]
 [0.17391119]]


In [3]:
# insert a bias value of 1 into the inputs
def insert_bias(_inputs):    
    return np.insert(_inputs, 0, 1, axis=1)

inputs = insert_bias(inputs)
print(inputs)

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


### Implement an activation function

The activation of each neuron $j$ using activation function $g$ is given by:

$$y_j = g(\sum_{i=0}^m w_{ij}x_i)=\begin{cases}1 \quad \text{  if  }g(\sum_{i=0}^m w_{ij}x_i)>0 \\ 0 \quad \text{  if  } g(\sum_{i=0}^m w_{ij}x_i) \leq 0 \end{cases}$$

Implement an activation function according to the above equation. Here are several things to consider:
* What parameters do you need to pass to this function?
* How could you use numpy to compute $\vec{y}$ instead of writing a for loop to compute each $y_j$ individually? 
* What kind of object is this function going to return?


In [4]:
# TODO: complete this function
def calculate_activations(_inputs, _weights):
    
    _activations = np.dot(_inputs, _weights)
    
    return np.where(_activations>0,1,0)

test_weights = np.random.rand(n_in+1, n_out) * (1 / math.sqrt(n_in+1))
test_activations = calculate_activations(inputs, test_weights)
print(test_activations)

[[1]
 [1]
 [1]
 [1]]


### Update the weight vector

Let $y_j$ be the output of the $j^{th}$ neuron, and $t_j$ the target for that neuron, and $\eta$ (eta) the learning rate. 

$$w_{ij} \leftarrow w_{ij} - \eta(y_j - t_j) \cdot x_i$$

In [2]:
# TODO: complete this function
def update_weights(_inputs, _targets, _activations, _weights):
    
    _weights -= eta*np.dot(np.transpose(_inputs),_activations-_targets)
    
    print(f'error:\n{_activations-_targets}')
    print(f'inputs transposed:\n{np.transpose(_inputs)}')    
    print(f'weight vector:\n{_weights}')
    
    return _weights

test_weights = update_weights(inputs, targets, test_activations, test_weights)

NameError: name 'inputs' is not defined

### Train the model

Now that you have imeplemented the ```calculate_activations``` function and ```update_weights``` function, we can start training the Perceptron model. There are 3 steps in training:
1. calculate the activation based on the current weights.
2. update the weight vector based on the gradient of the error for this time step.
3. repeat for $n$ iterations.



In [6]:
iterations = 5

for i in range(iterations):
    print(f'\niteration: {i+1}')
    activations = calculate_activations(inputs, weights)
    weights = update_weights(inputs, targets, activations, weights)


iteration: 1
error:
[[1]
 [0]
 [0]
 [0]]
inputs transposed:
[[1 1 1 1]
 [0 0 1 1]
 [0 1 0 1]]
weight vector:
[[0.26386536]
 [0.2929082 ]
 [0.17391119]]

iteration: 2
error:
[[1]
 [0]
 [0]
 [0]]
inputs transposed:
[[1 1 1 1]
 [0 0 1 1]
 [0 1 0 1]]
weight vector:
[[0.06386536]
 [0.2929082 ]
 [0.17391119]]

iteration: 3
error:
[[1]
 [0]
 [0]
 [0]]
inputs transposed:
[[1 1 1 1]
 [0 0 1 1]
 [0 1 0 1]]
weight vector:
[[-0.13613464]
 [ 0.2929082 ]
 [ 0.17391119]]

iteration: 4
error:
[[0]
 [0]
 [0]
 [0]]
inputs transposed:
[[1 1 1 1]
 [0 0 1 1]
 [0 1 0 1]]
weight vector:
[[-0.13613464]
 [ 0.2929082 ]
 [ 0.17391119]]

iteration: 5
error:
[[0]
 [0]
 [0]
 [0]]
inputs transposed:
[[1 1 1 1]
 [0 0 1 1]
 [0 1 0 1]]
weight vector:
[[-0.13613464]
 [ 0.2929082 ]
 [ 0.17391119]]


### Test the model

Now we feed the trained model a test set to see how accurate the model is.  

In [7]:
test = np.array([[1,0],[1,1],[0,1],[0,0]])
test_target = np.array([[1],[1],[1],[0]])
test = insert_bias(test)
activations = calculate_activations(test, weights)

# check the accuracy of your trained model
accuracy = 0.0
for i in range(len(test_target)):
    if test_target[i] == activations[i]: accuracy += 1 
print(f'accuracy: {(accuracy / len(test_target))*100.0}%')

accuracy: 100.0%


### Bonus Task

Train your model to learn the XOR operation. 